FROM nginx:latest

COPY build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY runtime-env.sh /usr/share/nginx

RUN chmod +x /usr/share/nginx/runtime-env.sh

EXPOSE 3000

# Production default values, can be overridden during runtime
ENV API_ENDPOINT=https://reviewerapi.mrcabot.com/api
ENV CLIENT_ID=df068761-b323-4309-ae7a-2fd1abc2780c
ENV AUTHORITY=https://login.microsoftonline.com/common
ENV SCOPE=api://reviewer.mrcabot.com/user_impersonation

CMD ["/bin/sh", "-c", "/usr/share/nginx/runtime-env.sh && nginx -g \"daemon off;\""]
