FROM nginx:latest

COPY build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY runtime-env.sh /usr/share/nginx

RUN chmod +x /usr/share/nginx/runtime-env.sh

EXPOSE 3000

# Production default values, can be overridden during runtime
ENV API_ENDPOINT=https://reviewerapi.mrcabot.com/api

CMD ["/bin/sh", "-c", "/usr/share/nginx/runtime-env.sh && nginx -g \"daemon off;\""]
