
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewer-api
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reviewer-api
  template:
    metadata:
      labels:
        app: reviewer-api
        aadpodidbinding: reviewer-api-label
    spec:
      containers:
      - name: reviewer-api
        image: ghcr.io/jasoncabot-ms/reviewer/api:v1.4
        ports:
        - containerPort: 5000
        env:
        - name: "ASPNETCORE_ENVIRONMENT"
          value: "Production"
        - name: "ASPNETCORE_FORWARDEDHEADERS_ENABLED"
          value: "true"
        - name: "AllowedOrigin"
          value: "https://reviewer.mrcabot.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviewer-ui
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reviewer-ui
  template:
    metadata:
      labels:
        app: reviewer-ui
        aadpodidbinding: reviewer-ui-label
    spec:
      containers:
      - name: reviewer-ui
        image: ghcr.io/jasoncabot-ms/reviewer/ui:v1.4
        ports:
        - containerPort: 3000
        env:
        - name: "API_ENDPOINT"
          value: "https://reviewerapi.mrcabot.com/api"
        - name: "CLIENT_ID"
          value: "df068761-b323-4309-ae7a-2fd1abc2780c"
        - name: "AUTHORITY"
          value: "https://login.microsoftonline.com/common"
        - name: "SCOPE"
          value: "api://reviewer.mrcabot.com/user_impersonation"
